"""Generates docs/demo.md — my Demo Mode presenter script — from demo_content.py.

    cd backend && python -m app.demo.generate_demo_docs

Every problem title and every right/wrong solution in the document is read
straight from app/demo/demo_content.py at generation time, so the script and
the running app can never drift apart. To change a problem, edit
demo_content.py, re-run verify_demo_content, then re-run this. To change the
narrative, edit the text below.
"""

import re
from pathlib import Path

from app.demo import demo_content as content

# backend/app/demo/generate_demo_docs.py -> repository root -> docs/demo.md
DOC_PATH = Path(__file__).resolve().parents[3] / "docs" / "demo.md"

# Every NeuroCode doc opens with the logo and ends with the same copyright
# line. They're added here, at generation time, so regenerating demo.md
# always keeps them.
DOC_HEADER = '<div align="center">\n\n<img src="../frontend/src/assets/logo-mark.png" alt="NeuroCode logo" width="160"/>\n\n</div>\n\n'
DOC_FOOTER = '\n\n---\n\n<div align="center">\n\n© 2026 NeuroCode\n\n</div>\n'


def _normalize_dashes(text: str) -> str:
    """Docs house style: no em dashes. Each one (with its surrounding spaces)
    becomes a single space. Applied to the generated document only — the
    in-app demo content in demo_content.py is left unchanged."""
    return re.sub(r"[ \t]*—[ \t]*", " ", text)

LANGUAGE_LABELS = {"python": "Python", "javascript": "JavaScript", "cpp": "C++"}


def _code_block(language: str, code: str) -> str:
    return f"```{language}\n{code.rstrip()}\n```\n"


def _solutions(problem: dict) -> str:
    """Right and wrong solution for every language a problem supports."""
    parts = []
    for language, pair in problem["solutions"].items():
        label = LANGUAGE_LABELS[language]
        parts.append(f"**{label} — correct**\n\n{_code_block(language, pair['correct'])}")
        parts.append(f"**{label} — wrong.** {pair['wrong_explanation']}\n\n{_code_block(language, pair['wrong'])}")
    return "\n".join(parts)


def _problem_section(heading: str, problem: dict) -> str:
    return (
        f"#### {heading}\n\n"
        f"{problem['description']}\n\n"
        f"Expected complexity: `{problem['expected_complexity']}`\n\n"
        f"{_solutions(problem)}"
    )


def _practice_section() -> str:
    parts = ["### Practice (9 problems, Python / JavaScript / C++)\n"]
    for p in content.PRACTICE_PROBLEMS:
        heading = f"{p['title']} — {p['difficulty']} · {p['topic']} · key `{p['key']}`"
        if p.get("anti_pattern_trigger"):
            heading += " · ANTI-PATTERN TRIGGER"
        parts.append(_problem_section(heading, p))
    return "\n".join(parts)


def _challenge_section() -> str:
    parts = [f"### Challenge Gate — {content.CHALLENGE_NODE_KEY} (3 problems, Python)\n"]
    for i, p in enumerate(content.CHALLENGE_PROBLEMS, start=1):
        parts.append(_problem_section(f"Q{i}. {p['title']} — {p['difficulty']}", p))
    return "\n".join(parts)


def _assessment_section() -> str:
    parts = ["### Assessments (2 assessments × 3 questions, Python)\n"]
    for a in content.ASSESSMENTS:
        parts.append(
            f"#### {a['name']} (`{a['key']}`) — topics: {', '.join(a['topics'])}\n\n"
            f"Unlocks when: **{a['unlock_rule']['description']}**\n"
        )
        for i, q in enumerate(a["questions"], start=1):
            parts.append(_problem_section(f"{a['name']} Q{i}. {q['title']}", q).replace("#### ", "##### ", 1))
    return "\n".join(parts)


def _interview_section() -> str:
    parts = ["### Mock Interview (3 topics, Python)\n"]
    for t in content.MOCK_INTERVIEW_TOPICS:
        parts.append(_problem_section(f"Topic \"{t['topic']}\": {t['title']} — {t['difficulty']}", t))
    return "\n".join(parts)


def _integrity_section() -> str:
    rows = "\n".join(f"- **{g['label']}** (`{g['event_type']}`): {g['how_to_trigger']}" for g in content.INTEGRITY_TESTING_GUIDE)
    return f"## How I test the integrity signals\n\nThe same guide is shown inline on the active demo assessment page.\n\n{rows}\n"


def build_document() -> str:
    persona = content.DEMO_PERSONA["display_name"]
    cohort_names = ", ".join(m["name"] for m in content.DEMO_COHORT)
    roadmap_order = " → ".join(topic for topic, _ in content.DEMO_ROADMAP_TOPICS)
    trigger = next(p for p in content.PRACTICE_PROBLEMS if p.get("anti_pattern_trigger"))
    a1, a2 = content.ASSESSMENTS

    return f"""# NeuroCode Demo Mode — Presenter Script

> Generated from `backend/app/demo/demo_content.py` by `python -m app.demo.generate_demo_docs`.
> Don't edit the problem sections by hand — edit the content file and regenerate.

## What Demo Mode is

I built Demo Mode so I can present NeuroCode live without depending on luck. Normally every problem, assessment
question and interview question is generated by AI at runtime, so no two runs look the same. In Demo Mode the
*questions* are fixed and hand-authored, so I can rehearse the exact walkthrough. Everything else is the real
system: every submission is executed by Piston and graded by the real grader, analyzed by the real Tree-sitter
analyzer, reordered by the real adaptive roadmap rule, and proctored and integrity-scored by the real detectors and
scoring rules. Every demo solution below has been proven through that pipeline (`python -m app.demo.verify_demo_content`).
Demo data lives in its own `demo_*` tables, so nothing I do in Demo Mode touches real student data. My XP, level
and streak are the one deliberate exception: they are real.

## Before I present (one-time setup)

1. Apply migrations `026` to `035` from `database/schema/` in the Supabase SQL editor, in order.
2. In `backend/.env`, set `OWNER_EMAIL` to my own login email and `DEMO_MODE_PASSCODE` to a passcode only I know.
   Restart the backend; the startup warning about these two settings should be gone.
3. Optional: set `VITE_OWNER_EMAIL` in `frontend/.env` to the same email.
4. Start Piston (Docker Desktop → `wsl` → `cd ~/piston && docker compose up -d`) and run
   `cd backend && python -m app.demo.verify_demo_content` — it must end with `ALL DEMO CONTENT VERIFIED`.

## Switching Demo Mode on and off

- **On:** Administration page → **Demo Mode** section → flip the toggle. The first time in a browser session I'm asked
  for the Demo Mode passcode. The toggle turns green and a **Demo Mode** badge appears in the top bar.
- **Off:** click **Exit Demo** (or flip the toggle back). No passcode is needed to leave.
- While it's on, my name, email and photo are replaced by the **{persona}** persona with the NeuroCode logo mark.
- Switching on or off never changes my real roadmap, submissions, assessments or credentials.

## Run of show

The order matters: it guarantees I never hit an unexpected lock. The demo roadmap starts as **{roadmap_order}**.

1. **Dashboard.** Point out the {persona} greeting and the Demo Mode badge. XP, level and streak are my real values.
2. **Roadmap.** Arrays is active and everything else is locked. The note under the list explains this is a 5-topic demo
   roadmap; the real one has 10.
3. **Practice: the adaptive moment.** Topic `Arrays`, difficulty `easy`, then **Generate Problem (Gemini)** until
   **{trigger['title']}** appears. Paste the **Python wrong** solution and submit:
   - Tests: 1/5 pass (real execution, real expected/actual output).
   - Code Analysis flags a *linear membership check*, and says Hash Maps was moved earlier.
   - Back on the Roadmap, **Hash Maps has jumped from last place to second.**
   Then paste the **Python correct** solution and submit: 5/5 pass, no inefficiencies. Open the GPT or Claude option in
   the model menu to show the real subscription paywall.
4. **Complete topics.** Use **Mark Complete** on the active topics in order: Arrays → Hash Maps → Strings (or
   Arrays → Strings if I skipped step 3). Each completion awards real XP. This satisfies Assessment 1's rule:
   *{a1['unlock_rule']['description']}*
5. **Assessment 1 — {a1['name']}.** Start it, show the inline integrity guide, and switch tabs once to show a live
   *Tab Switching* event. Paste each question's correct solution and submit.
   - Pasting counts as a real *Large Paste* event (−8 each), tab switch −5, camera alert −10, typing-rhythm alert −6;
     below 60 the attempt is flagged and can't pass. Three pastes plus one tab switch = 71, which still passes.
   - Keep the camera on and stay in frame, or repeated camera alerts will flag the attempt.
6. **Challenge Gate — {content.CHALLENGE_NODE_KEY}.** Roadmap → {content.CHALLENGE_NODE_KEY} → **Take Challenge Gate**. Submit a wrong
   solution once to show a failure, then solve all 3. The topic completes (+100 XP), which satisfies Assessment 2's rule:
   *{a2['unlock_rule']['description']}*
7. **Assessment 2 — {a2['name']}.** Same flow as Assessment 1.
8. **Credentials.** Pick the assessment and tier (pre-selected to the tier I actually earned) → **Issue Demo Credential**
   → **View Certificate** → **Copy Verification Link** and open it: it shows *"This is a demo credential"*.
9. **Mock Interview.** Topic `Arrays`, `Strings` or `Hash Maps` → solve under the real timer.
10. **My Submissions.** Expand the example submission to show the teacher comment.
11. **Educator Portal.** The cohort is {cohort_names} plus my own live row as {persona}. Click any row for the timeline.
    On Administration, the User Management table shows the demo cohort with the real role dropdown and reset menu.
12. **Exit Demo.**

{_integrity_section()}
## Resetting between runs

Every button on the Administration page confirms first, and clears only its own module.

| Button | What it clears |
|---|---|
| Dashboard | Reverses exactly the XP Demo Mode awarded me and recalculates my level. Real XP and streak stay. |
| Roadmap | Demo topic progress; Hash Maps goes back to last place. |
| Practice | My posts in demo problem discussions (the seeded examples stay). |
| Challenge Gate | Solved Challenge Gate questions and its pass status. |
| Mock Interview | Demo interview sessions. |
| My Submissions | Graded demo submissions and their teacher comments; the example submission is re-created. |
| Assessment | Demo assessment attempts, scores and proctoring logs. |
| Credentials | Issued demo credentials. |
| Cohort | Runs the real admin full reset on {cohort_names}, then restores their starting progress. |

To rehearse from scratch: Roadmap, Challenge Gate, Assessment, Credentials, Practice, My Submissions, Mock Interview,
then Dashboard last.

## The persona and the demo cohort

**{persona}** is the identity I present under, so my personal name, email and photo never appear on the projector.
**{cohort_names}** are clearly fictional accounts with `@example.com` addresses. They are real database rows, so the
real admin role and reset actions work on them unchanged, and they carry a permanent `is_demo_cohort` flag that
excludes them from every real leaderboard, cohort view, user list, analytics query and admin count — whether Demo Mode
is on or off. They exist only to give the educator view something realistic to show.

## Fixed demo content

{_practice_section()}
{_challenge_section()}
{_assessment_section()}
{_interview_section()}"""


def main() -> None:
    document = DOC_HEADER + build_document().rstrip() + DOC_FOOTER
    DOC_PATH.write_text(_normalize_dashes(document), encoding="utf-8")
    print(f"Wrote {DOC_PATH}")


if __name__ == "__main__":
    main()
