// Public "Get Started" explainer. Every landing-page Get Started / Sign In
// call-to-action points here instead of /login, because the deployed preview
// is a static frontend with no live backend: sign-in can't complete there.
// This page explains why, honestly and without apology, and routes visitors
// to the two real ways to experience NeuroCode — self-hosting it, or watching
// it run. /login itself is untouched and still works for local setups.
import { Link } from 'react-router-dom';
import { ArrowLeft, BookOpen, PlayCircle, Zap, User, Server, ArrowRight } from 'lucide-react';
import '@/styles/landing.css';
import Logo from '@/components/common/Logo';
import Reveal from '@/components/landing/Reveal';

const SETUP_GUIDE_URL = 'https://github.com/mibrahim-O2/NueroCode-Official/blob/main/docs/SETUP_AND_DEPLOYMENT.md';
const FULL_WALKTHROUGH_URL = 'https://youtu.be/S7R6AE9nWps';
const QUICK_DEMO_URL = 'https://youtu.be/LMY99wXn-QE';

const REASONS = [
  {
    icon: User,
    title: 'It’s a personal project',
    body:
      'I built NeuroCode as a personal project, not as a hosted commercial service. A public instance ' +
      'would mean holding strangers’ accounts, their code submissions, and the camera checks behind ' +
      'proctored assessments. Doing that responsibly is a service in its own right, and that isn’t ' +
      'what this project is.',
  },
  {
    icon: Zap,
    title: 'The AI free tier sets a hard ceiling',
    body:
      'Practice problems, Challenge Gates, assessments and mock interviews are all generated by AI and ' +
      'verified by actually running them. A single Challenge Gate alone generates ten problems. The ' +
      'free tier of the AI provider allows only a small number of requests per day, so a public backend ' +
      'would run out within a handful of real users. More hosting budget doesn’t raise that limit — it ' +
      'belongs to the API key, not the server.',
  },
];

export default function GetStarted() {
  return (
    <div className="landing-page min-h-screen px-6 py-10">
      <div className="mx-auto max-w-3xl">
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 text-sm transition-opacity hover:opacity-80"
          style={{ color: 'var(--l-text-secondary)' }}
        >
          <ArrowLeft className="h-4 w-4" /> Back to NeuroCode
        </Link>

        <Reveal>
          <div className="mt-8 flex flex-col items-center text-center">
            <Logo variant="icon" size={84} animated />
            <p className="mt-6 text-xs font-semibold uppercase tracking-widest" style={{ color: 'var(--l-orange)' }}>
              Get Started
            </p>
            <h1 className="mt-3 font-heading text-3xl font-bold sm:text-4xl" style={{ color: 'var(--l-text-primary)' }}>
              This preview runs without a live backend — on purpose
            </h1>
            <p className="mt-4 max-w-2xl text-base leading-relaxed" style={{ color: 'var(--l-text-secondary)' }}>
              What you’re browsing is NeuroCode’s real frontend, deployed as a static site. Everything that
              makes the platform work — sandboxed code execution, AI problem generation, proctoring and
              credentials — lives in the backend, and I’ve chosen not to run that publicly. Here’s why.
            </p>
          </div>
        </Reveal>

        <div className="mt-10 grid gap-4 sm:grid-cols-2">
          {REASONS.map(({ icon: Icon, title, body }, i) => (
            <Reveal key={title} delay={i * 80}>
              <div className="l-card flex h-full flex-col gap-3 p-6">
                <Icon className="h-5 w-5" style={{ color: i === 0 ? 'var(--l-orange)' : 'var(--l-teal)' }} />
                <h2 className="font-heading text-lg font-semibold" style={{ color: 'var(--l-text-primary)' }}>
                  {title}
                </h2>
                <p className="text-sm leading-relaxed" style={{ color: 'var(--l-text-secondary)' }}>
                  {body}
                </p>
              </div>
            </Reveal>
          ))}
        </div>

        {/* Self-hosting is the way to use the real, fully functional platform. */}
        <Reveal delay={120}>
          <div className="l-card mt-4 flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:justify-between" style={{ borderColor: 'var(--l-orange)' }}>
            <div className="flex items-start gap-3">
              <Server className="mt-0.5 h-5 w-5 shrink-0" style={{ color: 'var(--l-orange)' }} />
              <div>
                <h2 className="font-heading text-lg font-semibold" style={{ color: 'var(--l-text-primary)' }}>
                  Run the real thing yourself
                </h2>
                <p className="mt-1 text-sm leading-relaxed" style={{ color: 'var(--l-text-secondary)' }}>
                  With your own free API key, the complete platform runs on your machine — every module,
                  fully working. The setup guide walks you through it step by step.
                </p>
              </div>
            </div>
            <a
              href={SETUP_GUIDE_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex shrink-0 items-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition-transform hover:scale-[1.03]"
              style={{ backgroundColor: 'var(--l-orange)', color: '#1A0900' }}
            >
              <BookOpen className="h-4 w-4" /> Open the Setup Guide
            </a>
          </div>
        </Reveal>

        {/* Two separate video links: the full walkthrough and the short demo. */}
        <Reveal delay={160}>
          <div className="mt-10 text-center">
            <h2 className="font-heading text-xl font-semibold" style={{ color: 'var(--l-text-primary)' }}>
              Or watch it running
            </h2>
            <div className="mt-5 flex flex-col items-center justify-center gap-3 sm:flex-row">
              <a
                href={FULL_WALKTHROUGH_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-full px-6 py-3.5 text-sm font-semibold transition-transform hover:scale-[1.03]"
                style={{ backgroundColor: 'var(--l-orange)', color: '#1A0900' }}
              >
                <PlayCircle className="h-4 w-4" /> Watch the Full Walkthrough
              </a>
              <a
                href={QUICK_DEMO_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-full border px-6 py-3.5 text-sm font-semibold transition-transform hover:scale-[1.03]"
                style={{ borderColor: 'var(--l-teal)', color: 'var(--l-teal)' }}
              >
                <PlayCircle className="h-4 w-4" /> Watch the Quick Demo
              </a>
            </div>
          </div>
        </Reveal>

        {/* Kept for anyone running the backend locally per the setup guide. */}
        <p className="mt-12 text-center text-xs" style={{ color: 'var(--l-text-muted)' }}>
          Already running the backend locally?{' '}
          <Link to="/login" className="inline-flex items-center gap-1 font-semibold hover:underline" style={{ color: 'var(--l-orange)' }}>
            Sign in <ArrowRight className="h-3 w-3" />
          </Link>
        </p>
      </div>
    </div>
  );
}
